const db =
{
  "aue": [
    ["a", "Here, use intelligence & sensibility;"],
    ["b", "have faith in Aue & your abilities."],
    ["c", "This is knowledge, to be shared, preserved, for joy."],
    ["d", "It is shared to you, rejoice!"],
    ["e", "Record & preach the joy."],
    ["f", "Nature & bodily constitution is formed now only;"],
    ["g", "after death is scattering."],
    ["h", "Primitive evolution gave joy & woe in sentience."],
    ["i", "Life, evolved together, shares the universe."],
    ["j", "Time, volatile, should be precious & used well."],
    ["k", "Know of woe, & seek joy with joy & praise."],
    ["l", "Trust & rely on nature & society."],
    ["m", "Oppose harm to it, & bolster good."],
    ["n", "Have empathy, & seek others' emulation."],
    ["o", "Some beings incite woe;"],
    ["p", "protect yourself & joy, & seek less belligerence."],
    ["q", "Some beings ignorantly feed woe, so exhibit Aue."],
    ["r", "Keep critical faith in science & knowledge;"],
    ["s", "wielded for joy, impedes known woe, grow it."]
  ],
  "interpretations": [
    ["Group revision", "Revise Aue & life with others, recite & chant, & record & preach the proceedings.", "abcdeklmnq"],
    ["Personal revision", "Revise Aue regularly throughout life, & record & summarise your relationship with it.", "abcde"],
    ["Aue literacy", "Promote literacy, & guard the meaning of Aue, also through translation.", "bceklmnq"],
    ["Aue celebration", "Celebrate with others the event of personal understanding of Aue, & faith in it. Record this understanding & the celebration itself.", "bdeq"],
    ["Austerity", "Mitigate austerity of essential produce, & be humble during abundance. Do not hoard or fight.", "bhilmnopq"],
    ["Education", "Enact & improve teaching in universal equity, balancing knowledge & investigation, reason & trust, humility & freedom, reality & fantasy, sanctity & impiety.", "ceklmnrs"],
    ["Conversation", "Keep knowledge & communication thriving - it alleviates from unconsciousness. Do not dominate conversation.", "chilrs"],
    ["Reflection", "Regularly reflect upon your interactions with reality, & the diverse far-reaching impact in all you do, & Aue & other beings' impact in your life.", "dehikln"],
    ["Gratitude", "Thank all those who bring you joy, celebrate this, & appreciate thanks to you. Be mindful of joy's diversity.", "dlnq"],
    ["Ecology", "The natural environment is our greatest fortune - protect it from pollution & exploit that may augment danger.", "fghiklmopqrs"],
    ["Corpse donation", "Once sentience in a being is dead the corpse may relieve others of woe through donation of tissue & organs.", "fgiklmnrs"],
    ["Divine vanity", "Free will is a product of evolution, & therefore deities are grossly improbable. It is vain to believe otherwise.", "fhir"],
    ["Bodily violation", "Do not violate another being's bodily constitution unless it could be their will. Suspended with lack of reciprocation.", "fhkmnoprs"],
    ["Health", "Keep yourself healthy & your environment hygienic & your immunity strong, & mitigate disease & its transmission.", "fjklmnprs"],
    ["Assisted suicide", "If a person is in great incurable pain, that they wish with sobriety & sanity their expedited death, permit it in the least painful method sought.", "fjkmnrs"],
    ["Materialism", "Swap possessions with others with joy, & seek experience over material goods, for experience is indefinitely tangible.", "gjkmn"],
    ["Promises", "Only declare promises you know you can keep, & if expectations must be changed seek consent from the other. Promises to the dead are meaningless.", "glm"],
    ["Consciousness", "Our minds are of our evolution, & our consciousness is found only within our bodies.", "hir"],
    ["Phobias", "Seek effective help in correcting phobias, for reliability & capability for both yourself & others. But do understand real situational dangers.", "hjkrs"],
    ["Charity", "Be charitable to others in need, & seek for the systems of plight to be reformed or destroyed.", "hilmnopq"],
    ["Veganism", "Seek to exclude, as far as is possible & practicable, all forms of exploitation of, & cruelty to, animals for food, clothing or any other purpose.", "hiklmnqrs"],
    ["Abortion", "Pregnancy is of bodily constitution, permitting termination before the unborn may feel woe. Soothe emotions by aiding other life to flourish & grow.", "hiknprs"],
    ["Responsible parenthood", "Plan your parenthood carefully. Use contraceptive & fertility methods as desired. Consider adoption after one biological child.", "ijknqrs"],
    ["Cooperation", "Encourage cooperation over competition in all disciplines except recreation.", "ijlrs"],
    ["Borrow reality", "Know we borrow the present from future beings and our future selves. Keep and ensure a healthy reality.", "iklmnrs"],
    ["Research participation", "Be aware of safe medical or scientific research, & participate & benefit with joy. Also donating bodily material, such as matched blood or tissue or hair.", "iklmnrs"],
    ["Existence", "To us the universe is perfect as it needed to be so for our existence.", "ir"],
    ["Slavery", "Find & eliminate enslavement or encouragement into so, & ensure executives similarly laboured themselves.", "jklmnopq"],
    ["Shame", "Do not cast shame for nudity, adult & consenting sexuality, or other victimless recreation, only perhaps suggest alternatives.", "jkns"],
    ["Exercise", "In recreational or healthful exercise seek use for this kinetic energy potential.", "jks"],
    ["Technological inertia", "Seek the propagation of improved socially valuable technology or methodology, as for some hardship we will benefit.", "jmrs"],
    ["Judgement", "Judge others only by their actions proven true, weighing their material conditions with their actions' severity.", "klmnopqrs"],
    ["Reconciliation", "Sincerely & appropriately correct & resolve & mitigate personal wrongdoing. Accept others seeking reconciliation with you also.", "klmn"],
    ["Truth", "Avoid lies, feigning, hypocrisy, & misinformation, including to yourself, & champion truth where lies are given. Lies are socially & scientifically unhealthy.", "lmoprs"],
  ]
}
