const db =
{
  "aue": [
    ["a", "Here, use intelligence & serious attitude;"],
    ["b", "have faith in Aue & your ability to understand."],
    ["c", "This is knowledge, to be shared, preserved, inspiring joy."],
    ["d", "It is shared to you, rejoice!"],
    ["e", "Record & preach the joy.<br>"],
    ["f", "The universe is over 13.7 billion years old."],
    ["g", "Only now nature & our bodily constitution is formed & the future is too short to reform it."],
    ["h", "We & the universe will scatter in death."],
    ["i", "We are sentient – thinking so existing – able to suffer & enjoy, developed through primitive evolution."],
    ["j", "We share the universe with life which evolved alongside our ancestors."],
    ["k", "Time, volatile, should be precious & used well.<br>"],
    ["l", "Know of suffering, & seek out joy with joy & praise."],
    ["m", "Seek out all sentient beings & remember them always."],
    ["n", "Trust, & aid trust, & rely on nature & the society of sentience – it can bring joy."],
    ["o", "Avoid harm to it, & bolster goodness."],
    ["p", "Embrace empathy, love others & yourself, encouraging reciprocation & emulation.<br>"],
    ["q", "Some beings seek suffering;"],
    ["r", "protect yourself & joy, & seek to reduce belligerence."],
    ["s", "Some beings unknowingly limit joy, so demonstrate Aue.<br>"],
    ["t", "Keep critical faith in science & knowledge."],
    ["u", "Wield it for joy, understand it to avoid suffering, contribute to it."]
  ],
  "interpretations": [
    ["Group revision", "Revise Aue & life with others, & record & preach the proceedings.", "abcdelmnops"],
    ["Personal revision", "One should revise Aue regularly throughout life, & record & summarise one’s relationship to it.", "abcde"],
    ["Aue literacy", "Promote literacy, & guard the recorded meaning of Aue, also through translation. Aue should be made accessible to all sentient beings, through literacy or codified example.", "bcelmnops"],
    ["Aue celebration", "Celebrate with others the event of personal understanding of Aue, & faith in it. Record this understanding & the celebration itself.", "bdes"],
    ["Austerity", "Mitigate austerity of essential produce, & be humble during abundance. Do not hoard or fight.", "bijimnopqrs"],
    ["Primary education", "Seek, improve, & enact the most effective methods of teaching children in universal equity, balancing knowledge & investigation, reason & trust, humility & freedom, reality & fantasy, sanctity & impiety.", "celmnoptu"],
    ["Conversation", "Knowledge & communication is all that alleviates us from unconsciousness, so keep it thriving. Do not dominate conversation.", "cijntu"],
    ["Reflection", "Regularly reflect upon your interactions with reality, & the diverse far-reaching impact in all you do, & Aue in your life, since your last reflection.", "dilp"],
    ["Ecology", "The natural environment is fortunate – protect it from inorganic pollution if it may augment danger.", "ghijlmnoqrstu"],
    ["Corpse donation", "Once sentience in a being is dead the corpse may relieve others of suffering through donation of tissue & organs. Else, respect the corpse that was cultivated as the habitat of a fellow being.", "ghjlmnoptu"],
    ["Bodily violation", "Do not violate another being's bodily constitution unless it could be their will.", "gilopqrtu"],
    ["Assisted suicide", "If a person is in great incurable pain, that they wish with sobriety & sanity their expedited death, it should be permitted in the least painful method sought.", "gklmoptu"],
    ["Materialism", "Swap possessions with others with joy, and seek out experience over material goods, for they are indefinitely tangible.", "hklop"],
    ["Promise", "Only declare promises you know you can keep, and if expectations must be changed seek consent from the other. Promises to the dead are meaningless.", "hno"],
    ["Phobias", "Seek out effective help in correcting phobias, making you more reliable & capable for both yourself & others. But do make sure real situational dangers are strongly understood.", "ikltu"],
    ["Charity", "Be charitable to others in need, & seek for the systems of their plight to be reformed or destroyed.", "ijimnopqrs"],
    ["Veganism", "Seek to exclude, as far as is possible & practicable, all forms of exploitation of, & cruelty to, animals for food, clothing or any other purpose.", "ijlmnopstu"],
    ["Abortion", "A pregnant person may seek termination of their pregnancy until the unborn may feel suffering. Soothe emotions by aiding other life to flourish & grow.", "ijlprtu"],
    ["Responsible parenthood", "Plan your parenthood carefully. Use contraceptive & fertility methods as desired. Consider adoption before having a second biological child.", "jklpstu"],
    ["Cooperation", "Encourage cooperation over competition in all disciplines, reserving competition for recreation.", "jkmntu"],
    ["Living donation", "Be aware of the bodily material you can safely donate, & seek out how to contribute, such as blood donation, tissue HLA registration, & hair donation. Accepting these is also joy.", "jlmnoptu"],
    ["Research participation", "Be aware of, & participate in with joy, safe medical or scientific research.", "jlmnoptu"],
    ["Slavery", "Seek out and eliminate the enslavement of others, or encouragement into servitude, & ensure executives similarly laboured themselves.", "klmnopqrs"],
    ["Shame", "Do not cast shame for nudity, adult & consenting sexuality, or other victimless recreation, only perhaps educate on problems.", "klpu"],
    ["Exercise", "In recreational or healthful exercise seek out useful applications for the kinetic energy potential.", "klu"],
    ["Technological inertia", "Support the propagation of improved socially valuable technology or methodology, as for some investment or hardship we will reap benefits.", "kotu"],
    ["Judgement", "Judge others only by their actions, & only as far as you can understand their material conditions weighed with the actions’ severity.", "lmnopqrstu"],
    ["Hygiene", "Keep yourself and your environment hygienic & your immunity strong, & mitigate the spread of disease.", "lmnopstu"],
    ["Truth", "Avoid lies, feigning, & misinformation, including to yourself, & champion truth where lies are given, as lies are socially & scientifically unhealthy.", "noqrtu"]
  ]
}
