const db =
{
  "aue": [
    ["a", "Here, use intelligence & sensibility;"],
    ["b", "have faith in Aue & your ability to understand."],
    ["c", "This is knowledge, to be shared, preserved, inspiring joy."],
    ["d", "It is shared to you, rejoice!"],
    ["e", "Record & preach the joy.<br>"],
    ["f", "Nature & our bodily constitution is formed now only & time too short to reform it."],
    ["g", "We & the universe will scatter in death."],
    ["h", "Primitive evolution gave joy & woe, sentience an acute form."],
    ["i", "We share the universe with life which evolved alongside our ancestors."],
    ["j", "Time, volatile, should be precious & used well.<br>"],
    ["k", "Know of woe, & seek out joy with joy & praise."],
    ["l", "Seek out all sentient beings & remember them always."],
    ["m", "Trust, & aid trust, & rely on nature & the society of sentience – a source of joy."],
    ["n", "Avoid harm to it, & bolster goodness."],
    ["o", "Embrace empathy, love others & yourself, encouraging reciprocation & emulation.<br>"],
    ["p", "Some beings incite woe;"],
    ["q", "protect yourself & joy, & seek to reduce belligerence."],
    ["r", "Some beings ignorantly foster woe, so demonstrate Aue.<br>"],
    ["s", "Keep critical faith in science & knowledge."],
    ["t", "Wield it for joy, know it to avoid woe, grow it."]
  ],
  "interpretations": [
    ["Group revision", "Revise Aue & life with others, & record & preach the proceedings.", "abcdeklmnor"],
    ["Personal revision", "Revise Aue regularly throughout life, & record & summarise your relationship with it.", "abcde"],
    ["Aue literacy", "Promote literacy, & guard the recorded meaning of Aue, also through translation. Aue should be made accessible to all sentient beings, through literacy or codified example.", "bceklmnor"],
    ["Aue celebration", "Celebrate with others the event of personal understanding of Aue, & faith in it. Record this understanding & the celebration itself.", "bder"],
    ["Austerity", "Mitigate austerity of essential produce, & be humble during abundance. Do not hoard or fight.", "bhihlmnopqr"],
    ["Primary education", "Seek, improve, & enact the most effective methods of teaching children in universal equity, balancing knowledge & investigation, reason & trust, humility & freedom, reality & fantasy, sanctity & impiety.", "ceklmnost"],
    ["Conversation", "Keep knowledge & communication thriving - it alleviates from unconsciousness. Do not dominate conversation.", "chimst"],
    ["Reflection", "Regularly reflect upon your interactions with reality, & the diverse far-reaching impact in all you do, & Aue & other beings' impact in your life.", "dehiklmo"],
    ["Gratitude", "Thank all those who bring you joy, celebrate this, & appreciate thanks to you. Be mindful of joy's diversity.", "dlmor"],
    ["Ecology", "The natural environment is our greatest fortune - protect it from pollution & exploit that may augment danger.", "fghiklmnpqrst"],
    ["Corpse donation", "Once sentience in a being is dead the corpse may relieve others of woe through donation of tissue & organs. Else, respect the corpse that was cultivated as the habitat of a fellow being.", "fgiklmnost"],
    ["Bodily violation", "Do not violate another being's bodily constitution unless it could be their will. Suspended with lack of reciprocation.", "fhknopqst"],
    ["Health", "Keep yourself healthy & your environment hygienic & your immunity strong, & mitigate disease & its transmission.", "fjklmnoqst"],
    ["Assisted suicide", "If a person is in great incurable pain, that they wish with sobriety & sanity their expedited death, permit it in the least painful method sought.", "fjklnost"],
    ["Materialism", "Swap possessions with others with joy, & seek out experience over material goods, for they are indefinitely tangible.", "gjkno"],
    ["Promises", "Only declare promises you know you can keep, & if expectations must be changed seek consent from the other. Promises to the dead are meaningless.", "gmn"],
    ["Phobias", "Seek out effective help in correcting phobias, to reliablity & capablity for both yourself & others. But do understand real situational dangers.", "hjkst"],
    ["Charity", "Be charitable to others in need, & seek for the systems of plight to be reformed or destroyed.", "hihlmnopqr"],
    ["Veganism", "Seek to exclude, as far as is possible & practicable, all forms of exploitation of, & cruelty to, animals for food, clothing or any other purpose.", "hiklmnorst"],
    ["Abortion", "Pregnancy is of bodily constitution, & permit termination before the unborn may feel woe. Soothe emotions by aiding other life to flourish & grow.", "hikoqst"],
    ["Responsible parenthood", "Plan your parenthood carefully. Use contraceptive & fertility methods as desired. Consider adoption after one biological child.", "ijkorst"],
    ["Cooperation", "Encourage cooperation over competition in all disciplines except recreation.", "ijlmst"],
    ["Living donation", "Seek contribution of bodily material you can safely donate, such as matched blood or tissue or hair. Accepting these is also joy.", "iklmnost"],
    ["Research participation", "Be aware of safe medical or scientific research, & participate with joy.", "iklmnost"],
    ["Slavery", "Seek out & eliminate enslavement or encouragement into so, & ensure executives similarly laboured themselves.", "jklmnopqr"],
    ["Shame", "Do not cast shame for nudity, adult & consenting sexuality, or other victimless recreation, only perhaps suggest alternatives.", "jkot"],
    ["Exercise", "In recreational or healthful exercise seek out use for this kinetic energy potential.", "jkt"],
    ["Technological inertia", "Seek the propagation of improved socially valuable technology or methodology, as for some hardship we will reap benefits.", "jnst"],
    ["Judgement", "Judge others only by their actions proven true, weighing their material conditions with their actions' severity.", "klmnopqrst"],
    ["Reconciliation", "Sincerely & appropriately correct & resolve & mitigate personal wrongdoing.", "klmno"],
    ["Truth", "Avoid lies & feigning & misinformation, including to yourself, & champion truth where lies are given. Lies are socially & scientifically unhealthy.", "mnpqst"]
  ]
}
